

# Libreria Pandas

## 1. Introducción

En  Computación  y  Ciencia  de datos,  *Pandas*  es  una  biblioteca de  software  escrita  como  extensión  de NumPy para manipular, analizar, limpiar y explorar datos para el lenguaje de programación Python.

Pandas nos permite analizar big data y sacar conclusiones basadas en teorías estadísticas.

Por tratarse de una librería especializada en el procesamiento de datos estructurados, muchas de las operaciones implementadas en Python siguen la lógica de funcionamiento de NumPy, la librería para el procesamiento de arrays.

Además, con ayuda de Pandas podemos abordar problemas de Análisis de Datos y Análisis Exploratorio de Datos en nuestros proyectos de Ciencia de Datos y Machine Learning. 
Esto muchas veces requiere el uso de herramientas de visualización de datos que en el fondo usan librerías como Matplotlib

Podemos: limpiar  conjuntos  de  datos  desordenados  y  hacerlos  legibles  y  relevantes.  También se puede eliminar filas que no son relevantes o que contienen valores incorrectos, como valores vacíos o NULL.

El nombre "Pandas" hace referencia tanto a "Datos de panel" como a "Análisis de datos de Python".

Pandas resulta fundamental en el ciclo de vida de un proyecto de Ciencia de Datos y o de Machine Learning en las siguientes fases:

- En la limpieza y exploración de los datos
- En el manejo de datos faltantes o de valores extremos
- En el análisis (descriptivo, explicativo, predictivo o prescriptivo) de los datos
- En el pre-procesamiento de los datos y la extracción de características
- En la comunicación de resultados

Vale la pena aclarar que podemos usar Pandas en un proyecto de Machine Learning siempre y cuando los datos que estemos procesando sean datos estructurados.

Además de permitir manipular únicamente datos estructurados, existe otra situación en la cual es recomendable el uso de Pandas: cuando tenemos “datos pequeños” es decir cuando nuestro set de datos se puede almacenar en memoria en un sólo ordenador.

Cuando tenemos datasets gigantescos, que superan la capacidad de memoria de nuestro computador, es recomendable usar otras librerías como por ejemplo PySpark, Dask o Polars.

Sin embargo, es importante resaltar que estas librerías usan una sintaxis muy similar a la usada por Pandas para el procesamiento de datasets pequeños, así que el hecho de aprender Pandas nos permitirá reducir posteriormente la curva de aprendizaje de estas otras librerías en caso de que sea necesario aprenderlas.


## 2. Instalación

Lo  primero que debemos hacer para poder utilizarla es importarla con import. Como estándar se utilizan las siglas pd como alias.

Previamente se debe haber instalado (pip install pandas)

In [ ]:
import pandas as pd



La estructura de datos básica sobre la que se sustenta Pandas se denomina **serie**, la cual podríamos entender como una mezcla entre las estructuras de python : listas y los diccionarios.

Un nivel por encima de las series se sitúan los **DataFrame**, los cuales podemos entender como un conjunto de series combinadas. A continuación, veremos ambas estructuras en detalle.

## 3.	ESTRUCTURAS DE DATOS 1: SERIES

Técnicamente  entendemos  una  serie  como  un  array  n-dimensional  al  que  se  le  pueden  adjuntar etiquetas a sus ejes.


#### serie	  clave1	clave2	clave3
####      	      valor1	valor2	valor3


### a.	Definiendo Series

Lo vemos con un ejemplo:

In [3]:
# Paises y su poblacion
import pandas as pd

serieNumérica = pd.Series([47100396, 63644343, 81881238], index=["España", "Francia", "Alemania"])
print(serieNumérica)

print("")


#Paises y su capital : lista e indice
serieString = pd.Series(["Madrid", "Paris", "Berlín"], index=["España", "Francia", "Alemania"])
print("Series con listas e indices: ")
print(serieString)
print("----------------------------")
#Paises y su capital : diccionario
serieString = pd.Series({"Madrid": 'España', "Paris": 'Francia', "Berlín": 'Alemania'})
print
print(serieString)
print("----------------------------")

#Errores con las longitudes de los indices
serieString = pd.Series(["Madrid", "Paris", "Berlín"], index=["España", "Francia"])  #ERROR
serieString = pd.Series(["Madrid", "Paris"], index=["España", "Francia"])

España      47100396
Francia     63644343
Alemania    81881238
dtype: int64

Series con listas e indices:
España      Madrid
Francia      Paris
Alemania    Berlín
dtype: object
----------------------------
Madrid      España
Paris      Francia
Berlín    Alemania
dtype: object
----------------------------

ValueError: Length of values (3) does not match length of index (2)

En el caso de strings, al no ser de tipo primitivo, aparece como de tipo object.
 
En caso de que nuestros elementos que conforman el índice y el numero de elementos de contenido sean diferentes tendremos un error de ejecución.

Si desconociéramos algún valor, podríamos rellenar los elementos vacíos con el elemento None.


En cambio, si en vez de None utilizasemos un string, el tipo dejaría de ser primitivo para ser tipo  object, como demuestra el siguiente ejemplo.

In [ ]:
import pandas as pd

serieNumérica = pd.Series([47100396, 63644343, None], index=["España", "Francia", "Alemania"])
print(serieNumérica)

print(" ")

serieNumérica = pd.Series([47100396, 63644343, ""], index=["España", "Francia", "Alemania"])
print(serieNumérica)

España      47100396.0
Francia     63644343.0
Alemania           NaN
dtype: float64
España      47100396
Francia     63644343
Alemania
dtype: object

Tambien podemos crear series partiendo de otras estructuras, como de diccionario filtrando por índice, en este caso será el índice quien fije el tamaño. 

Y en caso de que filtremos por elementos que no existen en la lista, Python los rellenara  automaticamente con None.

Por ejemplo:

In [ ]:

diccionarioCapitales = {"Italia": "Roma", "Portugal": "Lisboa", "Polonia": 'Varsovia'}
print(diccionarioCapitales)

seriestringFiltrada = pd.Series(diccionarioCapitales, index=["Italia", "Portugal"])
print(seriestringFiltrada)

serieStringFiltrada = pd.Series(diccionarioCapitales, index=["Italia", "Portugal", "Bélgica"])
print(serieStringFiltrada)

{'Italia': 'Roma', 'Portugal': 'Lisboa', 'Polonia': 'Varsovia'}
Italia        Roma
Portugal    Lisboa
dtype: object
Italia        Roma
Portugal    Lisboa
Bélgica        NaN
dtype: object

### b. Accediendo a los elementos de una Serie

Para acceder a un determinado elemento podemos utilizar su posición o su índice.

In [ ]:
print("Accediendo a los valores mediante desde [] " + serieStringFiltrada[1])         #no recomendada. Usar iloc
print("Accediendo a los valores mediante desde iloc[] " + serieStringFiltrada.iloc[1])

print("Accediendo a los valores mediante desde [] " + serieStringFiltrada["Italia"])
print("Accediendo a los valores mediante desde loc[] " + serieStringFiltrada.loc["Italia"])

Accediendo a los valores mediante desde [] Lisboa
Accediendo a los valores mediante desde iloc[] Lisboa
Accediendo a los valores mediante desde [] Roma
Accediendo a los valores mediante desde loc[] Roma

C:\Users\encar\AppData\Local\Temp\ipykernel_20496\2429405982.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Accediendo a los valores mediante desde [] " + serieStringFiltrada[1]) #no recomendada

Para recorrer la lista completa podemos utilizar cualquier bucle, utilizando preferentemente el for.

In [ ]:
# Recorriendo La serie completa
for pais in serieStringFiltrada:
    print(pais)

Roma
Lisboa
nan

### C. Trabajando con aleatorios y grandes series

En machine learning normalmente se trabaja con grandes cantidades de datos. Una manera simple de conseguirlo es generándolos aleatoriamente.

Además, generar series aleatorias es muy práctico, ya que nos será útil para simular datos de prueba.
Para generar los números aleatorios, además de Pandas, necesitaremos de la librería Numpy.
Importamos Numpy si no lo hemos hecho ya.

¡OJO! Funciones como print() dejan de ser prácticas cuando las series alcanzan cierto tamaño, ya que inundarían la pantalla con demasiados datos.

Es por ello por lo que se hace necesario el uso de funciones alternativas como head() o tail(). Por defecto muestran los 5 primero o ultimos valores

In [ ]:
import numpy as np

# Creamos una Lista compuestas por 10.800 números aleatorios comprendidos entre 10 y 99
serieNumerosAleatorios = pd.Series(np.random.randint(10,99,10008))

serieNumerosAleatorios.head()

serieNumerosAleatorios.tail()

# Mostramos Los 10 primeros elementos
serieNumerosAleatorios.head(10)

#Mostramos Los 10 últimos elementos
serieNumerosAleatorios.tail(10)

9998     17
9999     14
10000    46
10001    29
10002    20
10003    30
10004    95
10005    73
10006    29
10007    29
dtype: int32

### d. Aplicando operaciones sobre una Serie

Dado que las series se pueden recorrer como cualquier otra estructura iterativa, siempre podemos implementar las operaciones que necesitemos por nosotros mismos.

Si queremos sumar todos los elementos de una serie, podríamos:

In [ ]:
# Sumatorio de forma manual
total = 0
for elemento in serieNumerosAleatorios:
    total += elemento
print(total)


# Sumatorio utilizando funciones de Numpy

sumatorio = np.sum(serieNumerosAleatorios)
print(sumatorio)

541168
541168

Si tomamos por ejemplo la media, tendríamos:

In [ ]:
# Media de forma manual
total = 0
for elemento in serieNumerosAleatorios:
    total += elemento
print(total/len(serieNumerosAleatorios))


# Media utilizando funciones de Numpy

media = np.mean(serieNumerosAleatorios)
print(media)

54.073541167066345
54.073541167066345

Ocurre lo mismo con otras operaciones, como por ejemplo añadir o restar un valor constante a todos los
elementos de la serie. implementándolo por nosotros mismos quedaría del siguiente modo

In [ ]:
serieNumerosAleatorios = pd.Series(np.random.randint(10,99,100))
serieNumerosAleatoriosCopia = serieNumerosAleatorios.copy()


#Restamos 10 a todos Los elementos
for indice, elemento in serieNumerosAleatorios.items():
    serieNumerosAleatorios[indice] = elemento - 10
# Comprobamos como La media se ha reducido en 10
print(np.mean(serieNumerosAleatorios))


## Mientras que esa misma operación se podría realizar de la siguiente manera

serieNumerosAleatoriosCopia -= 10
# Comprobamos como La media se ha incrementado en 10, volviendo a su estado original
print(np.mean(serieNumerosAleatoriosCopia))

44.18
44.18



La potencia de la serie nos permite aplicar la operación directamente:

In [ ]:
serieNumerosAleatoriosCopia -= 10
# Comprobamos como La media se ha incrementado en 10, volviendo a su estado original
print(np.mean(serieNumerosAleatoriosCopia))

A esto se le conoce como VECTORIZACIÓN y podremos implementarlo para:

- Operaciones matemáticas básicas
- Operaciones entre series (serie1 + serie2)
- Operaciones de numpy
- Cadenas de caracteres. A través del espacio de nombres .str podemos aplicar funciones string a una serie

Internamente se utilizan funciones avanzadas de numpy, esto hace que sea más eficiente que recorrelo con un bucle.

In [5]:
import pandas as pd

# DataFrame de ejemplo con una columna de strings
df_ejemplo = pd.DataFrame({
    'ID': [1, 2, 3],
    'Nombres': ['ESPAÑA', 'Francia', 'Alemania'],
    'Valores': [100, 200, 300]
})

df_ejemplo['Nombres_min'] = df_ejemplo['Nombres'].str.lower()

print(df_ejemplo)

   ID   Nombres  Valores Nombres_min
0   1    ESPAÑA      100      españa
1   2   Francia      200     francia
2   3  Alemania      300    alemania


## 4. ESTRUCTURAS DE DATOS: DATAFRAME

El DataFrame constituye el verdadero corazón de Pandas y será **la clase que utilizaremos de forma más habitual**. 

Un DataFrame puede entenderse como un array de nxm dimensiones.

### a. Creación de Dataframes

Los DataFrame se pueden crear de muy diversas maneras.

- Con listas para filas, columnas y datos ```pd.DataFrame(datos, filas, columnas)```
- Creando series a partir de diccionarios y posteriormente creación del dataframe a partir de estas

In [1]:
#dataframe vacío 
import pandas as pd

df = pd.DataFrame()
print (df)

#Crear un dataframe con Listas

filas = ["ventas1","ventas2","ventas3"]
columnas = ["zonaA","zonaB","zonaC"]
datos = [[123, 423, 100],[678, 234, 123], [345, 432, 789]]

dataframe = pd.DataFrame(datos, filas, columnas)

print("Imprimir dataframe")
print(dataframe)

#Usando series combinadas con diccionarios 

paisl = pd.Series({'Nombre': 'España',
                    "Capital": "Madrid",
                    "Población": 47108396})

pais2 = pd.Series({'Nombre': 'Francia',
                    "Capital": "París",
                    "Población": 63644343})

pais3 = pd.Series({'Nombre': 'Alemania',
                    "Capital": 'Berlin',
                    "Población": 81881238})

dataFramePaises = pd.DataFrame([paisl, pais2, pais3], index=['Pais 1', 'País 2', 'País 3'])

print("Imprimir dataframe paises ")
dataFramePaises.head()

Empty DataFrame
Columns: []
Index: []
Imprimir dataframe
         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas2    678    234    123
ventas3    345    432    789
Imprimir dataframe paises

          Nombre Capital  Población
Pais 1    España  Madrid   47108396
País 2   Francia   París   63644343
País 3  Alemania  Berlin   81881238

### b. Operaciones con Dataframes

#### I. Seleccionar y trabajar con elementos de un Dataframe

Si usamos el ejemplo anterior de creacion de dataframe con listas, podemos acceder a los elementos de la siguiente manera:


Para las filas debemos usar función .loc.

In [37]:
dataframe_sel = dataframe.loc[['ventas1','ventas2']]

print(dataframe_sel)

         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas2    678    234    123

In [38]:
print(dataframe)

         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas2    678    234    123
ventas3    345    432    789

Las columnas: si es más de una habría que meterlas dentro de una lista de listas como en el caso anterior

In [39]:
dataframe['zonaA']

ventas1    123
ventas2    678
ventas3    345
Name: zonaA, dtype: int64

Seleccionar un valor concreto del dataframe: fila y columna

In [40]:
dataframe.loc['ventas1']['zonaC']
# dataframe['ventas1']['zonaC'] -> Sentencia erronea. Intenta acceder por indice a columnas y no existen

100

Si queremos añadir una nueva columna: Por ejemplo que nos sume los valores de cada fila crearemos la columna de forma similar a una nueva clave en un diccionario.

In [ ]:
dataframe['TodasLasZonas'] = dataframe['zonaA'] + dataframe['zonaB'] + dataframe['zonaC']
                                                         
dataframe

# Borra datos en la Visualización (pondremos axis=1 cuando queramos indicar en pandas columnas)
dataframe.drop('TodasLasZonas', axis=1)

# Si queremos borrar datos definitivamente en el dataframe hay que usar inplace=true
dataframe.drop('TodasLasZonas', axis = 1, inplace = True)

# Si queremos borrar una fila pasa lo mismo, sin el inplace solo es un borrado visual.

dataframe.drop('ventas3', inplace=True) 
dataframe

# Ver el tamaño de nuestro dataframe. Tupla (número de filas, número de columnas)
dataframe.shape

(2, 3)

#### II. Seleccionar elementos de un Dataframe usando condiciones

Otra manera de crear las listas:

In [ ]:
filas ='ventas1 ventas2 ventas3'.split()

columnas = 'zonaA zonaB zonaC'.split()

datos = [[123,423,100],[678,234,123],[345,432,789]]
df = pd.DataFrame(datos, filas, columnas)

df

         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas2    678    234    123
ventas3    345    432    789

Si queremos seleccionar los valores que sean mayores a 400 crearemos una condicion que podemos aplicar o no a todo el dataframe

Para los que no cumplan la condición escribira **NaN** (Not a number - Valor faltante de tipo numérico)

Se mantiene la estructura

In [46]:
cond = df > 400

df[cond]

         zonaA  zonaB  zonaC
ventas1    NaN  423.0    NaN
ventas2  678.0    NaN    NaN
ventas3    NaN  432.0  789.0

Si queremos seleccionar los valores de una columna (Zona) en concreto que cumplan la condición de que sean mayor a 400, los que no cumplan la condición escribirá NaN.

**NaN es el valor faltante estándar en pandas para datos numéricos y permite operaciones matemáticas.**

In [47]:
cond = df['zonaB'] > 400
df[cond]

         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas3    345    432    789

Si queremos 2 condiciones de filtrado podemos utilizar los siguientes operadores lógicos:

**& es y (and)**

**| es o (or)**

In [ ]:
condicion = (df['zonaB']>100) & (df['zonaC']>700)
df[condicion]

#Ojo con esta diferencia

nuevo_df = df[condicion]

         zonaA  zonaB  zonaC
ventas3    345    432    789

#### III. Modificar indice de un dataframe

Partimos de la situación inicial del ejemplo usado hasta ahora en el que el índice es la lista de valores con los identificadores de las filas.

In [49]:
print("Índice del DataFrame:")
print(df.index)

Índice del DataFrame:
Index(['ventas1', 'ventas2', 'ventas3'], dtype='object')

In [ ]:
df

         zonaA  zonaB  zonaC
ventas1    123    423    100
ventas2    678    234    123
ventas3    345    432    789

El índice es una estructura que identifica de forma única cada fila. Actúa como una etiqueta o identificador para cada fila y permite acceder, manipular y organizar los datos de manera más eficiente.

PASO1: Debemos añadir una nueva columna con los datos que identifiquen al indice

In [50]:
dias = "dias1 dias2 dias3".split()
dias

df["nuevos dias"] = dias

df

         zonaA  zonaB  zonaC nuevos dias
ventas1    123    423    100       dias1
ventas2    678    234    123       dias2
ventas3    345    432    789       dias3

PASO2: realizamos la modificación del indice, aunque de esta manera es solo visual y simula el estar añadiendo una columna

In [ ]:
df.set_index("nuevos dias")
df

         zonaA  zonaB  zonaC nuevos dias
ventas1    123    423    100       dias1
ventas2    678    234    123       dias2
ventas3    345    432    789       dias3

PASO3: para que sea definitiva… debemos indicar ```ìnplace = True```

In [52]:
df.set_index("nuevos dias", inplace=True)

df

             zonaA  zonaB  zonaC
nuevos dias
dias1          123    423    100
dias2          678    234    123
dias3          345    432    789

El indice nos permitirá acceder a filas específicas usando ```.loc[indice]```

In [53]:
df.loc['dias1']

zonaA    123
zonaB    423
zonaC    100
Name: dias1, dtype: int64

También se podría hacer un multiindice

In [63]:

filas ='ventas1 ventas2 ventas3'.split()

columnas = 'zonaA zonaB zonaC'.split()

datos = [[123,423,100],[678,234,123],[345,432,789]]

df = pd.DataFrame(datos, filas, columnas)

df.set_index(["zonaA", "zonaB"], inplace=True)

df

             zonaC
zonaA zonaB
123   423      100
678   234      123
345   432      789

En este caso tendremos que acceder por indice y columna : ```.loc[indice, columna]```

In [64]:
df.loc[(123, 423), 'zonaC']

100

### ¡¡OJO!!: Un índice es un identificador simple o compuesto de una fila, no es una identificador único como una clave primaria. 

- Indice simple. ```.loc``` devolverá todas las filas que coincidan con ese indice
- Indice multinivel: ```.loc``` devolverá las filas que coincidan con los niveles especificados

In [65]:

data_simple = {
    'Población': [500000, 600000, 1000000, 700000],
    'País': ['España', 'España', 'Francia', 'Francia']
}
ciudades = ['Madrid', 'Madrid', 'París', 'París']

# Crear DataFrame con índice duplicado
df_simple = pd.DataFrame(data_simple, index=ciudades)

# Mostrar el DataFrame
print("DataFrame con índice simple duplicado:\n", df_simple)

# Acceder a todas las filas con índice 'Madrid'
print("\nFilas con índice 'Madrid':\n", df_simple.loc['Madrid'])

DataFrame con índice simple duplicado:
         Población     País
Madrid     500000   España
Madrid     600000   España
París     1000000  Francia
París      700000  Francia

Filas con índice 'Madrid':
         Población    País
Madrid     500000  España
Madrid     600000  España

In [66]:
# Crear datos
data_multinivel = {
    'Población': [500000, 300000, 1000000, 700000],
    'Idioma': ['Español', 'Español', 'Francés', 'Francés']
}
indice_multinivel = [('Madrid', 'Centro'), ('Madrid', 'Sur'), ('París', 'Centro'), ('París', 'Centro')]

# Crear DataFrame con índice multinivel
df_multinivel = pd.DataFrame(data_multinivel, index=pd.MultiIndex.from_tuples(indice_multinivel, names=['Provincia', 'Ciudad']))

# Mostrar el DataFrame
print("DataFrame con índice multinivel duplicado:\n", df_multinivel)

# Acceder a todas las filas con el índice ('París', 'Centro')
print("\nFilas con índice ('París', 'Centro'):\n", df_multinivel.loc[('París', 'Centro')])

DataFrame con índice multinivel duplicado:
                   Población   Idioma
Provincia Ciudad
Madrid    Centro     500000  Español
          Sur        300000  Español
París     Centro    1000000  Francés
          Centro     700000  Francés

Filas con índice ('París', 'Centro'):
                   Población   Idioma
Provincia Ciudad
París     Centro    1000000  Francés
          Centro     700000  Francés

#### IV. Tratar Datos en un Dataframe

##### - Valores NaN

Partimos del siguiente ejemplo

In [ ]:

dic = {'A':[3,5,np.nan], 'B':[3,5,6], 'C':[np.nan,7,np.nan]}

df = pd.DataFrame(dic)

df

     A  B    C
0  3.0  3  NaN
1  5.0  5  7.0
2  NaN  6  NaN

Eliminamos las filas donde hay nulos.

In [69]:
df.dropna()

     A  B    C
1  5.0  5  7.0

Para eliminar las columnas que tengan nulos (axis=1)

In [70]:
df.dropna(axis=1)

   B
0  3
1  5
2  6

Si queremos que los dos casos anteriores, queden permanentemente debemos añadir como antes inplace=true

Para modificar los valores nulos (rellenar los nulos con un valor) podemos usar la funcion ```fillna()```

In [ ]:
df.fillna(value=100)

       A  B      C
0    3.0  3  100.0
1    5.0  5    7.0
2  100.0  6  100.0

### - Eliminar filas o columnas con drop()

In [ ]:
df.drop('fila_a_eliminar', axis=0, inplace=True)

df.drop('columna_a_eliminar', axis=1, inplace=True)

### - Aplicar una funcion a filas o columnas con apply()

Muy habitual el uso de funciones lambda pero se puede pasar cualquier función

In [ ]:
df['columna'].apply(lambda x: x * 2)  # Multiplicar cada valor por 2

### - Agrupar datos 

La función groupby() permite agrupar datos en función de una o más columnas

In [73]:

data = {'Producto': ['A', 'A', 'B', 'B', 'C', 'C'],
        'Tienda': ['T1', 'T2', 'T1', 'T2', 'T1', 'T2'],
        'Ventas': [100, 150, 200, 250, 300, 350]}

df = pd.DataFrame(data)

# Calcular la media de ventas para cada combinación de Producto y Tienda
resultado_groupby = df.groupby(['Producto', 'Tienda'])['Ventas'].mean()
print(resultado_groupby)

Producto  Tienda
A         T1        100.0
          T2        150.0
B         T1        200.0
          T2        250.0
C         T1        300.0
          T2        350.0
Name: Ventas, dtype: float64

### - Crear pivot tables con pivot_table()
Para resumir y analizar grandes cantidades de datos.
Similar a group_by pero este permite varios niveles (Piensa en las pivot tables de excel)

In [74]:

data = {
    'Producto': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Tienda': ['T1', 'T2', 'T1', 'T2', 'T1', 'T2'],
    'Ventas': [100, 150, 200, 250, 300, 350]
}

df = pd.DataFrame(data)

# Crear una tabla dinámica con el promedio de ventas por tienda y producto
tabla_pivot = df.pivot_table(values='Ventas', index='Producto', columns='Tienda', aggfunc='mean')
print(tabla_pivot)

Tienda       T1     T2
Producto
A         100.0  150.0
B         200.0  250.0
C         300.0  350.0

### - Ordenar valores

En función de una o más columnas

In [75]:
df.sort_values(by=['Producto', 'Ventas'], ascending=[True, False])

  Producto Tienda  Ventas
1        A     T2     150
0        A     T1     100
3        B     T2     250
2        B     T1     200
5        C     T2     350
4        C     T1     300

#### - Identificar y borrar duplicados

Ojo, no siempre querremos borrar los duplicados. Tendremos que analizar qué significan en nuestro Dataframe.

In [ ]:
df.duplicated()  # Verifica si hay duplicados
df.drop_duplicates()  # Elimina duplicados

### - Contar valores

Podemos usar las funciones ```size()``` y ```count()```
Size cuenta todas las filas y count los valores no nulos

In [76]:
# Contar el total de filas por producto
conteo_size = df.groupby("Producto")["Ventas"].size()
print("Usando size():")
print(conteo_size)

Usando size():
Producto
A    2
B    2
C    2
Name: Ventas, dtype: int64

In [77]:
# Contar las filas no nulas por producto en la columna 'Ventas' usando count()
conteo_count = df.groupby("Producto")["Ventas"].count()
print("Usando count():")
print(conteo_count)

Usando count():
Producto
A    2
B    2
C    2
Name: Ventas, dtype: int64

#### Las funciones ```nlargest()```y ```nsmallest()``` no son funciones específicas de pandas pero podemos usarlas aplicadas a un dataframe

In [78]:
data = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas': [150, 300, 120, 450, 200]
}

df = pd.DataFrame(data)

print(df)

  Producto  Ventas
0        A     150
1        B     300
2        C     120
3        D     450
4        E     200

In [79]:
# Obtener los 3 productos con más ventas
top_3_ventas = df.nlargest(3, 'Ventas')
print(top_3_ventas)

  Producto  Ventas
3        D     450
1        B     300
4        E     200

#### V. Combinar Dataframes

Concatenamos los dos dataframe:

Tienen que coincidir los indices para poder realizar esta operación

In [ ]:
dic = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
dic1 = {'A':[10,11,12],'B':[13,14,15], 'B':[16,17,18]}

df = pd.DataFrame(dic)
df1 = pd.DataFrame(dic1)

df

pd.concat([df,df1])

    A   B    C
0   1   4  7.0
1   2   5  8.0
2   3   6  9.0
0  10  16  NaN
1  11  17  NaN
2  12  18  NaN

Si no coinciden se concatenan como columnas y se "rellena" con valores NaN

In [ ]:
dic = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
dic1 = {'D':[10,11,12],'E':[13,14,15], 'F':[16,17,18]}

df = pd.DataFrame(dic)
df1 = pd.DataFrame(dic1)

df

pd.concat([df,df1])

     A    B    C     D     E     F
0  1.0  4.0  7.0   NaN   NaN   NaN
1  2.0  5.0  8.0   NaN   NaN   NaN
2  3.0  6.0  9.0   NaN   NaN   NaN
0  NaN  NaN  NaN  10.0  13.0  16.0
1  NaN  NaN  NaN  11.0  14.0  17.0
2  NaN  NaN  NaN  12.0  15.0  18.0

Pueden estar en distinto orden

In [ ]:
dic = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
dic1 = {'C':[10,11,12],'B':[13,14,15], 'A':[16,17,18]}

df = pd.DataFrame(dic)
df1 = pd.DataFrame(dic1)

df

pd.concat([df,df1])

    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
0  16  13  10
1  17  14  11
2  18  15  12

Si queremos que lo concatene en horizontal

In [ ]:
pd.concat([df,df1],axis=1)

   A  B  C   C   B   A
0  1  4  7  10  13  16
1  2  5  8  11  14  17
2  3  6  9  12  15  18

#### VI. Mezclar dataframes (merge)

Permite integrar filas de dos DataFrames que contienen información en común en una o varias columnas o índices que se conocen como clave.

Se utiliza el método **merge** que puede tener los siguientes tipos:

- inner: intersección de conjuntos. Filas cuyos valores clave están en los dos dataframes
- outer: union de conjuntos. Las filas que no pueden emparejarse se completan con Nan
- left: se descartan las filas del segundo dataframe que no puedan emparejarse con alguna del primero a través de la clave
- right: se descartan las filas del primer dataframe que no puedan emparejarse con alguna del primero a través de la clave

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"Nombre":["Carmen", "Luis", "María"],  "Sexo":["Mujer", "Hombre", "Mujer"]})
df2 = pd.DataFrame({"Nombre":["María", "Pedro", "Luis"], "Edad":[25, 30, 18]})
df = pd.merge(df1, df2, on="Nombre", how="left")
print(df)

   Nombre    Sexo  Edad
0  Carmen   Mujer   NaN
1    Luis  Hombre  18.0
2   María   Mujer  25.0

#### VII. Otras operaciones con Dataframe

```describe()```Describe los datos del dataframe. Si es numérico tendremos la siguiente información para cada columna

. count - The number of not-empty values.

. mean - The average (mean) value.

. std - The standard deviation.

. min - the minimum value.

. 25% - The 25% percentile*.

. 50% - The 50% percentile*.

. 75% - The 75% percentile*.

. max - the maximum value.

In [ ]:
df.describe()

            Edad
count   2.000000
mean   21.500000
std     4.949747
min    18.000000
25%    19.750000
50%    21.500000
75%    23.250000
max    25.000000

In [ ]:
#valores unicos de una columna 
df['A'].unique()

#numero de valores que no se repiten
df['A'].nunique()

#numero de ocurrencias de cada valor 
df['A'].value_counts()

#nombres de filas y columnas
df.columns
df.index

#ordenar columnas
df.sort_values('B')

KeyError: 'A'

#### VIII. Reemplazar valores genéricos faltantes

In [ ]:
df = pd.DataFrame ({'one':[10,20,30,40,50,2000], 'two':[1000,0,30,40,50,60]})

print (df)

#remplaza 1000 con 10 y 2000 con 60
print (df.replace ({1000:10,2000:60}))

    one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60
   one  two
0   10   10
1   20    0
2   30   30
3   40   40
4   50   50
5   60   60

## 5. Manejo de Ficheros CSV
#### a. Leer el contenido de un csv

In [ ]:
import pandas as pd

df = pd.read_csv('courseid_7858_participants.csv')

df

,Nombre,Apellido(s),Número de ID,Dirección de correo,Departamento,Institución,Grupos
0,Daniel,Agustín Arroyo,1334886,dagustina01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
1,Álex,Blanco Benito,996944,ablancob07@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
2,Danut George Nicolae,Cobzaru,2021537,dgncobzaru01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
3,César Enrique,Corral Menéndez,780757,cecorralm01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
4,Encarnación,Delgado Hoyo,2140877,eedh08@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
5,Miguel,Díez de Toro,2096093,mdiezd06@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
6,Miguel,Frejo Marañón,2145014,mfrejom01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
7,Iván,Gómez Calvo,1098564,igomezc38@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
8,Iván,Gómez de Santiago,1008850,igomezd09@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
9,Samuel,Jiménez Rodero,1060658,master704@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
10,David,López Santos,1391750,david.lopez.santos@gmail.com,19002615,19002615_IES Arcipreste de Hita,NaN
11,Roberto,Marcos García,1135327,rmarcosg06@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
12,Miguel,Mendiola Aragonés,663580,mmendiolaa01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
13,Ramón,Panadero Dobarro,1008872,rpanaderod01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
14,Ricardo Manuel,Pascual García,1988194,rmpascualg01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
15,Jorge,Pastor Montero,679215,jpastorm06@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
16,David,Rodríguez Martín,2090670,drodriguezm132@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
17,Javier,Sánchez-Seco González,1197685,jsanchezsecog03@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
18,Valentina,Santiago Barrera,1946711,vsantiagob02@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN
19,Julia,Sobrado Jiménez,2096107,jsobradoj01@educastillalamancha.es,19002615,19002615_IES Arcipreste de Hita,NaN

#### b. Escribir en un CSV

Aplicamos un filtro al csv anterior, y su resultado lo volcamos en un nuevo csv:

In [ ]:
cond = df['Apellido(s)']>'L'

df2 = df[cond]

print(df2)

df2.to_csv('filter.csv')

            Nombre            Apellido(s)  Número de ID  \
10           David           López Santos       1391750
11         Roberto          Marcos García       1135327
12          Miguel      Mendiola Aragonés        663580
13           Ramón       Panadero Dobarro       1008872
14  Ricardo Manuel         Pascual García       1988194
15           Jorge         Pastor Montero        679215
16           David       Rodríguez Martín       2090670
17          Javier  Sánchez-Seco González       1197685
18       Valentina       Santiago Barrera       1946711
19           Julia        Sobrado Jiménez       2096107

                       Dirección de correo  Departamento  \
10            david.lopez.santos@gmail.com      19002615
11       rmarcosg06@educastillalamancha.es      19002615
12     mmendiolaa01@educastillalamancha.es      19002615
13     rpanaderod01@educastillalamancha.es      19002615
14     rmpascualg01@educastillalamancha.es      19002615
15       jpastorm06@educastillalamancha.es      19002615
16   drodriguezm132@educastillalamancha.es      19002615
17  jsanchezsecog03@educastillalamancha.es      19002615
18     vsantiagob02@educastillalamancha.es      19002615
19      jsobradoj01@educastillalamancha.es      19002615

                        Institución  Grupos
10  19002615_IES Arcipreste de Hita     NaN
11  19002615_IES Arcipreste de Hita     NaN
12  19002615_IES Arcipreste de Hita     NaN
13  19002615_IES Arcipreste de Hita     NaN
14  19002615_IES Arcipreste de Hita     NaN
15  19002615_IES Arcipreste de Hita     NaN
16  19002615_IES Arcipreste de Hita     NaN
17  19002615_IES Arcipreste de Hita     NaN
18  19002615_IES Arcipreste de Hita     NaN
19  19002615_IES Arcipreste de Hita     NaN

## 6.	Leer contenido de un html

https://es.wikipedia.org/wiki/Territorio_dependiente

Podemos leer los datos de un html para usar tablas mostrados en ellos, y guardarla en un dataframe para trabajar con los datos. 

Para ello necesitamos instalar : **pip install lxml**

La función read_html lee las tablas de una página html en una lista de dataframes

Lo habitual hoy en día es que las páginas nos ofrezcan APIs para obtener información pero en algún caso nos puede resultar útil

In [ ]:
import pandas as pd

datos = pd.read_html("https://es.wikipedia.org/wiki/Territorio_dependiente")

type(datos) #list

datos[0]

df = datos[0] #Generar dataframe y trabajar

## 7.	Trabajar con Bases de Datos

Pandas nos permite interactuar con una base de datos a través del método **to_sql**


El método to_sql() tiene varios parámetros que ajustan la funcionalidad y los datos que se envían a la base de datos. Estos incluyen:

- name: nombre de la tabla SQL (obligatorio)
- con: conexión proporcionada por sqlite o sqlalchemy (obligatorio)
- schema: esquema de la base de datos SQL
- if_exists: qué hacer si la tabla ya existe, ya sea 'fail' (fallar), 'replace' (reemplazar) o 'append' (agregar)
- index: si se debe escribir la columna de índice del DataFrame en la tabla o no
- index_label: el nombre para dar a la columna de índice si se escribe en la tabla
- chunksize: número de filas que se escribirán a la vez
- dtype: diccionario de todas las columnas y sus tipos de datos
- method: especificar la cláusula de inserción SQL

De forma similar la función read_sql() permite obtener datos de una o varias tablas, pasándole como parámetro la query
a realizar

Necesitaremos instalar **pip install pandas sqlalchemy** para la gestión con la base de datos y **pip install pymysql**


La función **create_engine** poporciona una conexión a una BD pasada en una URL

In [ ]:

import pandas as pd
import sqlalchemy as sq
from sqlalchemy import create_engine


# Reemplaza datos de conexión
engine = create_engine('mysql+pymysql://root:toor@localhost/temperaturas')  

datos = pd.read_html("https://es.wikipedia.org/wiki/Territorio_dependiente")

df = datos[0] #Generar dataframe y trabajar

df.to_sql('paises_dependientes', con=engine, if_exists='replace', index=False)

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

## 8. Otros formatos de datos 

Pandas trabaja con los siguientes tipos de archivos.
Tiene métodos para todos ellos **read_xxxx** y **to_xxxx**


CSV

Parquet (Formato recomendado por expertos en BI )

Excel

Json

Html

SQL


## 9. Gráficos en Panda

Pandas dispone de algunos métodos para visualización pero son muy básicos.
Hay disponibles diferentes librerías que permiten la personalización de los aspectos que configuran un gráfico para potenciar mucho la representación de los datos.

matplotlib como ya hemos visto es una de estas librerías y permite la customización de los aspectos del gráfico que quieras adaptar, para representar de la mejor forma los insights de los datos.

## 10. Miscelanea



Investigar cómo se debe trabajar con Strings 

https://pandas.pydata.org/docs/user_guide/text.html

Revisar documentación de Panda para conocer otras funciones como merge, join....

https://pandas.pydata.org/docs/user_guide/merging.html

Revisar cómo funciona sqalchemy

https://docs.sqlalchemy.org/en/20/core/engines.html

Guía de estilos de matplotlib

https://matplotlib.org/3.1.0/gallery/style_sheets/style_sheets_reference.html

## 11. Licencia de uso

Este documento está licenciado con Creative Commons

Resumen Librería Pandas © 2024 by Encarnación Delgado Hoyo is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

![](by-nc-sa.png)